export const bergenAirConditioners = [
    {
        id: 1,
        btiIdx: 7,
        art: "#789344",
        name: "Bergen BEI07FRD/BEO07FRD",
        brand: "Bergen",
        model: "BEI07FRD/BEO07FRD",
        price: "14999",
        discount: "-",
        available: true,
        description:
            "Інверторний кондиціонер Bergen з функцією охолодження та обогріву. Площа охолодження чи обігріву - до 20 м².",
        recommendedRoomArea: "20",
        generalCharacteristics: {
            compressorType: "inverter",
            compressor: "Toshiba",
            installation: "Настінне",
            temperatureRange: "Від -15 °С до + 50 °С",
            internalBlockSize: "715*285*194",
            externalBlockSize: "668*252*469",
            weightInternalUnit: "7,6",
            weightExternalUnit: "18",
            remoteControl: "+",
            bodyColor: "Білий",
            madeIn: "Китай",
            factory: "Midea",
            guarantee: "24",
            //         coolingCapacity: "3.5 kW",
            //         heatingCapacity: "3.5 kW",
            //         energyClass: "A++",
            //  Compressor type       noiseLevel: "21 dB",
            //         inverter: true,
            //         wifiControl: true,
            //         color: "White",
        },
        functions: {
            operationModes: "Охолодження/Обігрів/Осушення/Вентиляція/Авто",
            turboMode: "+",
            nightMode: "+",
            timer: "+",
            adjustingBlindsVertically: "+",
            automaticRestart: "+",
            selfCleaning: "+",
            disablingDisplayLighting: "+",
            dustFilter: "+",
        },
        specifications: {
            powerBto: "7000",
            coolingCapacity: "2,345",
            heatingCapacity: "2,433",
            SEER: "5.2",
            SCOP: "3.5",
            consumerPowerCoolingW: "730 (100~1074)",
            consumerPowerHeatingW: "670 (140~896)",
            energyClass: "A/A",
            noiseLevelIndoorUnit: "35/30,5/24,5/22",
            noiseLevelOutdoorUnit: "52,5",
            heatExchangersCoating: "Гідрофільне",
            MoistureRemoval: "1,0",
            MaximumConsumerCurrent: "9,0",
            powerSupply: "Indoor unit",
            connectingPipesDimensions: "6,35/9,52",
            highwayMaximumLength: "25",
            highwayMaximumHeightDifference: "10",
            freon: "R32",
            freonWeight: "0,42",

            images: {
                indoorUnit: "",
                outdoorUnit: "",
            },

            downloads: {
                userManual: "",
            },

            // availability: true,
            // stock: 25,
            // ratings: {
            //     average: 4.7,
            //     reviews: 145,
            // },
        },
    },

    {
        id: 2,
        btiIdx: 9,
        art: "#789345",
        name: "Bergen BEI09FRD/BEO09FRD",
        brand: "Bergen",
        model: "BEI09FRD/BEO09FRD",
        price: "15999",
        discount: "-",
        available: true,
        description:
            "Інверторний кондиціонер Bergen з функцією охолодження та обогріву. Площа охолодження чи обігріву - до 25 м².",
        recommendedRoomArea: "25",
        generalCharacteristics: {
            compressorType: "inverter",
            compressor: "Toshiba",
            installation: "Настінне",
            temperatureRange: "Від -15 °С до + 50 °С",
            internalBlockSize: "715*285*194",
            externalBlockSize: "668*252*469",
            weightInternalUnit: "7,6",
            weightExternalUnit: "18",
            remoteControl: "+",
            bodyColor: "білий",
            madeIn: "Китай",
            factory: "Midea",
            guarantee: "24",
            //         coolingCapacity: "3.5 kW",
            //         heatingCapacity: "3.5 kW",
            //         energyClass: "A++",
            //  Compressor type       noiseLevel: "21 dB",
            //         inverter: true,
            //         wifiControl: true,
            //         color: "White",
        },
        functions: {
            operationModes: "Охолодження/Обігрів/Осушення/Вентиляція/Авто",
            turboMode: "+",
            nightMode: "+",
            timer: "+",
            adjustingBlindsVertically: "+",
            automaticRestart: "+",
            selfCleaning: "+",
            disablingDisplayLighting: "+",
            dustFilter: "+",
        },
        specifications: {
            powerBto: "9000",
            coolingCapacity: "2,843",
            heatingCapacity: "2,960",
            SEER: "5.2",
            SCOP: "3.5",
            consumerPowerCoolingW: "886 (100~1074)",
            consumerPowerHeatingW: "820 (140~896)",
            energyClass: "A/A",
            noiseLevelIndoorUnit: "35/30,5/24,5/22",
            noiseLevelOutdoorUnit: "52,5",
            heatExchangersCoating: "Гідрофільне",
            MoistureRemoval: "1,0",
            MaximumConsumerCurrent: "9,0",
            powerSupply: "Внутрішній блок",
            connectingPipesDimensions: "6,35/9,52",
            highwayMaximumLength: "25",
            highwayMaximumHeightDifference: "10",
            freon: "R32",
            freonWeight: "0,42",

            images: {
                indoorUnit: "",
                outdoorUnit: "",
            },

            downloads: {
                userManual: "",
            },

            // availability: true,
            // stock: 25,
            // ratings: {
            //     average: 4.7,
            //     reviews: 145,
            // },
        },
    },

    {
        id: 3,
        btiIdx: 12,
        art: "#789346",
        name: "Bergen BEI12FRD/BEO12FRD",
        brand: "Bergen",
        model: "BEI12FRD/BEO12FRD",
        price: "17499",
        discount: "-",
        available: false,
        description:
            "Інверторний кондиціонер Bergen з функцією охолодження та обогріву. Площа охолодження чи обігріву - до 35 м².",
        recommendedRoomArea: "35",
        generalCharacteristics: {
            compressorType: "inverter",
            compressor: "Toshiba",
            installation: "Настінне",
            temperatureRange: "Від -15 °С до + 50 °С",
            internalBlockSize: "715*285*194",
            externalBlockSize: "720*270*495",
            weightInternalUnit: "7,5",
            weightExternalUnit: "21,4",
            remoteControl: "+",
            bodyColor: "білий",
            madeIn: "Китай",
            factory: "Midea",
            guarantee: "24",
            //         coolingCapacity: "3.5 kW",
            //         heatingCapacity: "3.5 kW",
            //         energyClass: "A++",
            //  Compressor type       noiseLevel: "21 dB",
            //         inverter: true,
            //         wifiControl: true,
            //         color: "White",
        },
        functions: {
            operationModes: "Охолодження/Обігрів/Осушення/Вентиляція/Авто",
            turboMode: "+",
            nightMode: "+",
            timer: "+",
            adjustingBlindsVertically: "+",
            automaticRestart: "+",
            selfCleaning: "+",
            disablingDisplayLighting: "+",
            dustFilter: "+",
        },
        specifications: {
            powerBto: "11450",
            coolingCapacity: "3,605",
            heatingCapacity: "3,708",
            SEER: "5.2",
            SCOP: "3.5",
            consumerPowerCoolingW: "1123 (280~1220)",
            consumerPowerHeatingW: "1028 (300~1260)",
            energyClass: "A/A",
            noiseLevelIndoorUnit: "37,5/33,5/26,5/23,5",
            noiseLevelOutdoorUnit: "56",
            heatExchangersCoating: "Гідрофільне",
            MoistureRemoval: "1,2",
            MaximumConsumerCurrent: "9,2",
            powerSupply: "Внутрішній блок",
            connectingPipesDimensions: "6,35/9,52",
            highwayMaximumLength: "25",
            highwayMaximumHeightDifference: "10",
            freon: "R32",
            freonWeight: "0,58",

            images: {
                indoorUnit: "",
                outdoorUnit: "",
            },

            downloads: {
                userManual: "",
            },

            // availability: true,
            // stock: 25,
            // ratings: {
            //     average: 4.7,
            //     reviews: 145,
            // },
        },
    },

    {
        id: 4,
        btiIdx: 18,
        art: "#789347",
        name: "Bergen BEI18FRD/BEO18FRD",
        brand: "Bergen",
        model: "BEI18FRD/BEO18FRD",
        price: "30999",
        available: true,
        discount: "-",
        description:
            "Інверторний кондиціонер Bergen з функцією охолодження та обогріву. Площа охолодження чи обігріву - до 52 м².",
        recommendedRoomArea: "52",
        generalCharacteristics: {
            compressorType: "inverter",
            compressor: "Toshiba",
            installation: "Настінне",
            temperatureRange: "Від -15 °С до + 50 °С",
            internalBlockSize: "957*213*302",
            externalBlockSize: "805*330*554",
            weightInternalUnit: "10",
            weightExternalUnit: "32,7",
            remoteControl: "+",
            bodyColor: "білий",
            madeIn: "Китай",
            factory: "Midea",
            guarantee: "24",
            //         coolingCapacity: "3.5 kW",
            //         heatingCapacity: "3.5 kW",
            //         energyClass: "A++",
            //  Compressor type       noiseLevel: "21 dB",
            //         inverter: true,
            //         wifiControl: true,
            //         color: "White",
        },
        functions: {
            operationModes: "Охолодження/Обігрів/Осушення/Вентиляція/Авто",
            turboMode: "+",
            nightMode: "+",
            timer: "+",
            adjustingBlindsVertically: "+",
            automaticRestart: "+",
            selfCleaning: "+",
            disablingDisplayLighting: "+",
            dustFilter: "+",
        },
        specifications: {
            powerBto: "18000",
            coolingCapacity: "5,275",
            heatingCapacity: "5,569",
            SEER: "5.7",
            SCOP: "3.5",
            consumerPowerCoolingW: "1550（140~2300)",
            consumerPowerHeatingW: "1543（220~2350)",
            energyClass: "A+/A",
            noiseLevelIndoorUnit: "42,5/36/26",
            noiseLevelOutdoorUnit: "56",
            heatExchangersCoating: "Гідрофільне",
            MoistureRemoval: "1,8",
            MaximumConsumerCurrent: "13",
            powerSupply: "Внутрішній блок",
            connectingPipesDimensions: "6,35/12,7",
            highwayMaximumLength: "30",
            highwayMaximumHeightDifference: "20",
            freon: "R32",
            freonWeight: "1,08",

            images: {
                indoorUnit: "",
                outdoorUnit: "",
            },

            downloads: {
                userManual: "",
            },

            // availability: true,
            // stock: 25,
            // ratings: {
            //     average: 4.7,
            //     reviews: 145,
            // },
        },
    },

    {
        id: 5,
        btiIdx: 24,
        art: "#789348",
        name: "Bergen BEI24FRD/BEO24FRD",
        brand: "Bergen",
        model: "BEI24FRD/BEO24FRD",
        price: "39999",
        discount: "-",
        available: false,
        description:
            "Інверторний кондиціонер Bergen з функцією охолодження та обогріву. Площа охолодження чи обігріву - до 70 м².",
        recommendedRoomArea: "70",
        generalCharacteristics: {
            compressorType: "inverter",
            compressor: "Toshiba",
            installation: "Настінне",
            temperatureRange: "Від -15 °С до + 50 °С",
            internalBlockSize: "1040*220*327",
            externalBlockSize: "890*342*673",
            weightInternalUnit: "12,3",
            weightExternalUnit: "42,9",
            remoteControl: "+",
            bodyColor: "білий",
            madeIn: "Китай",
            factory: "Midea",
            guarantee: "24",
            //         coolingCapacity: "3.5 kW",
            //         heatingCapacity: "3.5 kW",
            //         energyClass: "A++",
            //  Compressor type       noiseLevel: "21 dB",
            //         inverter: true,
            //         wifiControl: true,
            //         color: "White",
        },
        functions: {
            operationModes: "Охолодження/Обігрів/Осушення/Вентиляція/Авто",
            turboMode: "+",
            nightMode: "+",
            timer: "+",
            adjustingBlindsVertically: "+",
            automaticRestart: "+",
            selfCleaning: "+",
            disablingDisplayLighting: "+",
            dustFilter: "+",
        },
        specifications: {
            powerBto: "24000",
            coolingCapacity: "7,034",
            heatingCapacity: "7,327",
            SEER: "5.7",
            SCOP: "3.5",
            consumerPowerCoolingW: "2503（420~3150)",
            consumerPowerHeatingW: "2282（300~2750)",
            energyClass: "A+/A",
            noiseLevelIndoorUnit: "45/40,5/36",
            noiseLevelOutdoorUnit: "59",
            heatExchangersCoating: "Гідрофільне",
            MoistureRemoval: "2,4",
            MaximumConsumerCurrent: "15,5",
            powerSupply: "Внутрішній блок",
            connectingPipesDimensions: "6,35/15,88",
            highwayMaximumLength: "50",
            highwayMaximumHeightDifference: "25",
            freon: "R32",
            freonWeight: "1,42",

            images: {
                indoorUnit: "",
                outdoorUnit: "",
            },

            downloads: {
                userManual: "",
            },

            // availability: true,
            // stock: 25,
            // ratings: {
            //     average: 4.7,
            //     reviews: 145,
            // },
        },
    },
];

export const rodaHeatConvectors = [{}];

export const ncEnergyPowerStation = [
    {
        id: 61,
        btiIdx: "index-electrostation-nc-clima-3",
        power: "3",
        article: "#1017",
        name: "NC ENERGY NCE3P3U24ua",
        controlType: "Інверторний",
        compatibility:
            "Електромережа/генератор/сонячні панелі/побутова техніка",
        weight: "36кг",
        battery: "LiFePO4",
        price: "50999",
        discount: "-",
        available: true,
        description:
            "Інверторна портативна зарядна станція на 3 кВт - NCE3P3U24ua",
        outputInterfaces:
            "USB-A/RS485 (підключення до ПК)/USB Wi-Fi (для живлення роутера)/Type-C/ USB 5V x 4 pcs/DC 12V x 2 (вихід постійного струму)/AC x 3 pcs",
        chargingTime: "≥2",
        dimensions: "522/655/382",
        inverterCharacteristics: {
            signalShape: "Чиста синусоїда",
            regulationOutputVoltage: "230В ±5%",
            outputFrequency: "50/60 (±0,2Гц)",
            peakEfficiency: "90%",
            standbyConsumption: "0,025кВт",
        },
        pvFotoModulesInput: {
            maximumChargeCurrent: "60 (±3)А",
            maximumCombinedChargeCurrent: "80 (±4)А",
            outputFrequency: "50/60 (±0,2)Гц",
            maximumEfficiency: "98%",
            noLoadVoltagePhotovoltaicModules: "145В",
            mpptVoltageRange: "30 ~ 120В",
        },
        aCInput: {
            regulationOfInputVoltage: "230В ±5%",
            inputVoltageRange: "90 – 280В",
            nominalInputFrequency: "50/60Гц (автоматичне визначення)",
            transmissionTime:
                "10 мс типовий (ДБЖ)/20 мс типовий (електроприлади)",
            maximumAlternatingChargeCurrent: "30 (±4)А",
        },
        lithiumBatteryData: {
            nominalVoltage: "25,6В",
            batteryCapacity: "125 А·год/3,5 кВт·год",
            nominalDischargeCurrent: "140А",
            workingTemperature: "60С (розряду)",
        },
        featuresAndGeneralDescription: {
            overloadProtection: "+",
            overHeatingProtection: "+",
            shortCircuitProtection: "+",
            type: "Мобільна система",
            installation: "Не потребує монтажу",
            guarantee: "24 міс.",
            color: "Білий",
            madeIn: "Китай",
            Plant: "MUST ENERGY",
            completeSet: "",
        },

        images: {
            imgFace: "images/nc-energy-3.png",
            imgProf: "",
        },

        downloads: {
            userManual: "",
        },

        // availability: true,
        // stock: 25,
        // ratings: {
        //     average: 4.7,
        //     reviews: 145,
        // },
    },

    {
        id: 62,
        article: "#1018",
        btiIdx: "index-electrostation-nc-clima-3_5",
        name: "NC ENERGY NCE3S5U24ua",
        power: "3,5",
        controlType: "Інверторний",
        compatibility:
            "Електромережа/генератор/сонячні панелі/побутова техніка",
        weight: "36кг",
        battery: "LiFePO4",
        price: "99999",
        discount: "-",
        available: true,
        description:
            "Зарядна станція повербанк NCE3S5U24ua - Зарядна станція 3,5 кВт",
        outputInterfaces:
            "USB-A/RS485 (підключення до ПК)/USB Wi-Fi (для живлення роутера)/Type-C/ USB 5V x 4 pcs/DC 12V x 2 (вихід постійного струму)/AC x 3 pcs",
        chargingTime: "≥2",
        dimensions: "522/655/382мм",
        inverterCharacteristics: {
            signalShape: "Чиста синусоїда",
            regulationOutputVoltage: "230В ±5%",
            outputFrequency: "50/60 (±0,2Гц)",
            peakEfficiency: "90%",
            standbyConsumption: "0,025кВт",
        },
        pvFotoModulesInput: {
            maximumChargeCurrent: "60 (±3)А",
            maximumCombinedChargeCurrent: "80 (±4)А",
            outputFrequency: "50/60 (±0,2)Гц",
            maximumEfficiency: "98%",
            noLoadVoltagePhotovoltaicModules: "145В",
            mpptVoltageRange: "30 ~ 120В",
        },
        aCInput: {
            regulationOfInputVoltage: "230В ±5%",
            inputVoltageRange: "90 – 280В",
            nominalInputFrequency: "50/60Гц (автоматичне визначення)",
            transmissionTime:
                "10 мс типовий (ДБЖ)/20 мс типовий (електроприлади)",
            maximumAlternatingChargeCurrent: "30 (±4)А",
        },
        lithiumBatteryData: {
            nominalVoltage: "25,6В",
            batteryCapacity: "125 А·год/3,5 кВт·год",
            nominalDischargeCurrent: "140А",
            workingTemperature: "60С (розряду)",
        },
        featuresAndGeneralDescription: {
            overloadProtection: "+",
            overHeatingProtection: "+",
            shortCircuitProtection: "+",
            type: "Мобільна система",
            installation: "Не потребує монтажу",
            guarantee: "24 міс.",
            color: "Білий",
            madeIn: "Китай",
            Plant: "MUST ENERGY",
            completeSet: "",
        },

        images: {
            imgFace: "images/NC-energy-3-5.png",
            imgProf: "",
        },

        downloads: {
            userManual: "",
        },

        // availability: true,
        // stock: 25,
        // ratings: {
        //     average: 4.7,
        //     reviews: 145,
        // },
    },
    {
        id: 63,
        article: "#1019",
        btiIdx: "index-electrostation-nc-clima-5_2",
        name: "NC ENERGY NCE5P5U48ua",
        power: "5,2",
        controlType: "Інверторний",
        compatibility:
            "Електромережа/генератор/сонячні панелі/побутова техніка",
        weight: "36кг",
        battery: "LiFePO4",
        price: "99999",
        discount: "-",
        available: true,
        description:
            "Зарядна станція повербанк NCE3S5U24ua - Зарядна станція 3,5 кВт",
        outputInterfaces:
            "USB-A/RS485 (підключення до ПК)/USB Wi-Fi (для живлення роутера)/Type-C/ USB 5V x 4 pcs/DC 12V x 2 (вихід постійного струму)/AC x 3 pcs",
        chargingTime: "≥2 год.",
        dimensions: "522/655/382мм",
        inverterCharacteristics: {
            signalShape: "Чиста синусоїда",
            regulationOutputVoltage: "230В ±5%",
            outputFrequency: "50/60 (±0,2Гц)",
            peakEfficiency: "90%",
            standbyConsumption: "0,025кВт",
        },
        pvFotoModulesInput: {
            maximumChargeCurrent: "60 (±3)А",
            maximumCombinedChargeCurrent: "80 (±4)А",
            outputFrequency: "50/60 (±0,2)Гц",
            maximumEfficiency: "98%",
            noLoadVoltagePhotovoltaicModules: "145В",
            mpptVoltageRange: "30 ~ 120В",
        },
        aCInput: {
            regulationOfInputVoltage: "230В ±5%",
            inputVoltageRange: "90 – 280В",
            nominalInputFrequency: "50/60Гц (автоматичне визначення)",
            transmissionTime:
                "10 мс типовий (ДБЖ)/20 мс типовий (електроприлади)",
            maximumAlternatingChargeCurrent: "30 (±4)А",
        },
        lithiumBatteryData: {
            nominalVoltage: "25,6В",
            batteryCapacity: "125 А·год/3,5 кВт·год",
            nominalDischargeCurrent: "140А",
            workingTemperature: "60С (розряду)",
        },
        featuresAndGeneralDescription: {
            overloadProtection: "+",
            overHeatingProtection: "+",
            shortCircuitProtection: "+",
            type: "Мобільна система",
            installation: "Не потребує монтажу",
            guarantee: "24 міс.",
            color: "Білий",
            madeIn: "Китай",
            Plant: "MUST ENERGY",
            completeSet: "",
        },

        images: {
            imgFace: "images/nc-clima-enerhy-station-5-2.png",
            imgProf: "",
        },

        downloads: {
            userManual: "",
        },

        // availability: true,
        // stock: 25,
        // ratings: {
        //     average: 4.7,
        //     reviews: 145,
        // },
    },
    {
        id: 64,
        btiIdx: "index-electrostation-nc-clima-5_5",
        article: "#1020",
        name: "NC ENERGY NCE5S10U48ua",
        power: "5,5",
        controlType: "Інверторний",
        compatibility:
            "Електромережа/генератор/сонячні панелі/побутова техніка",
        weight: "36кг",
        battery: "LiFePO4",
        price: "170999",
        discount: "-",
        available: false,
        description: "Потужні зарядні станції 5.5 кВт - серія NCE5S10U48ua",
        outputInterfaces:
            "USB-A/RS485 (підключення до ПК)/USB Wi-Fi (для живлення роутера)/Type-C/ USB 5V x 4 pcs/DC 12V x 2 (вихід постійного струму)/AC x 3 pcs",
        chargingTime: "≥2 год.",
        dimensions: "522/655/382мм",
        inverterCharacteristics: {
            signalShape: "Чиста синусоїда",
            regulationOutputVoltage: "230В ±5%",
            outputFrequency: "50/60 (±0,2Гц)",
            peakEfficiency: "90%",
            standbyConsumption: "0,025кВт",
        },
        pvFotoModulesInput: {
            maximumChargeCurrent: "60 (±3)А",
            maximumCombinedChargeCurrent: "80 (±4)А",
            outputFrequency: "50/60 (±0,2)Гц",
            maximumEfficiency: "98%",
            noLoadVoltagePhotovoltaicModules: "145В",
            mpptVoltageRange: "30 ~ 120В",
        },
        aCInput: {
            regulationOfInputVoltage: "230В ±5%",
            inputVoltageRange: "90 – 280В",
            nominalInputFrequency: "50/60Гц (автоматичне визначення)",
            transmissionTime:
                "10 мс типовий (ДБЖ)/20 мс типовий (електроприлади)",
            maximumAlternatingChargeCurrent: "30 (±4)А",
        },
        lithiumBatteryData: {
            nominalVoltage: "25,6В",
            batteryCapacity: "125 А·год/3,5 кВт·год",
            nominalDischargeCurrent: "140А",
            workingTemperature: "60С (розряду)",
        },
        featuresAndGeneralDescription: {
            overloadProtection: "+",
            overHeatingProtection: "+",
            shortCircuitProtection: "+",
            type: "Мобільна система",
            installation: "Не потребує монтажу",
            guarantee: "24 міс.",
            color: "Білий",
            madeIn: "Китай",
            Plant: "MUST ENERGY",
            completeSet: "",
        },

        images: {
            imgFace: "images/nc-clima-energy-station-5-5.png",
            imgProf: "",
        },

        downloads: {
            userManual: "",
        },

        // availability: true,
        // stock: 25,
        // ratings: {
        //     average: 4.7,
        //     reviews: 145,
        // },
    },
];
