export const bergenAirConditioners = [
    {
        id: 81,
        btiIdx: 87,
        art: "#889344",
        name: "RODA Stanard+ RSP-1500EU",
        brand: "RODA",
        model: "RSP-1500EU",
        price: "1899",
        discount: "-",
        available: true,
        description:
            "Конвектор RODA Stanard+ RSP-1500EU",
        recommendedRoomArea: "17",
        generalCharacteristics: {
            heaterType: "відкритий",
            installation: "З коліщатками/ніжками для переміщення/настінне",
            additionalCharacteristics: "Швидке і безшумне обігрівання. Робота за принципом природної конвекції повітря. Європейський нагрівальний елемент. Подвійна потужність нагрівального елементу з можливістю використання тільки 50%. Режим підтримки мінімальної температури +8 °C. Ручка для перенесення",
            // temperatureRange: "Від -15 °С до + 50 °С",
            internalBlockSize: "46 х 67.5 х 11.5",
            externalBlockSize: "50 х 86 х 12.5",
            weightInternalUnit: "4,7",
            weightExternalUnit: "5,7",
            remoteControl: "-",
            bodyColor: "Білий",
            madeIn: "Україна",
            brandCountry: "Germany",
            guarantee: "60",
            //         coolingCapacity: "3.5 kW",
            //         heatingCapacity: "3.5 kW",
            //         energyClass: "A++",
            //  Compressor type       noiseLevel: "21 dB",
            //         inverter: true,
            //         wifiControl: true,
            //         color: "White",
        },
        functions: {
            operationModes: "Обігрів",
            // turboMode: "+",
            // nightMode: "+",
            timer: "-",
            // adjustingBlindsVertically: "+",
            // automaticRestart: "+",
            // selfCleaning: "+",
            // disablingDisplayLighting: "+",
            // dustFilter: "+",
        },

        

        specifications: {
            // powerBto: "7000",
            // coolingCapacity: "2,345",
            // heatingCapacity: "2,433",
            // SEER: "5.2",
            // SCOP: "3.5",
            // consumerPowerCoolingW: "730 (100~1074)",
            protectionClass: "IP20",
            consumerPowerHeatingW: "1500",
            // energyClass: "A/A",
            // noiseLevelIndoorUnit: "35/30,5/24,5/22",
            // noiseLevelOutdoorUnit: "52,5",
            // heatExchangersCoating: "Гідрофільне",
            // MoistureRemoval: "1,0",
            // MaximumConsumerCurrent: "9,0",
            // powerSupply: "Indoor unit",
            // connectingPipesDimensions: "6,35/9,52",
            // highwayMaximumLength: "25",
            // highwayMaximumHeightDifference: "10",
            // freon: "R32",
            // freonWeight: "0,42",
            completeSet: "Конвектор, ніжки (2 шт.), кронштейни для настінного монтажу, інструкція",
            images: {
                indoorUnit: "",
                outdoorUnit: "",
            },

            downloads: {
                userManual: "",
            },

            // availability: true,
            // stock: 25,
            // ratings: {
            //     average: 4.7,
            //     reviews: 145,
            // },
            
        },
    },

    {
        id: 82,
        btiIdx: 88,
        art: "#889345",
        name: "RODA Standart+ RSP-2000EU",
        brand: "RODA",
        model: "RSP-2000EU",
        price: "1999",
        discount: "-",
        available: true,
        description:
            "Конвектор RODA Standart+ RSP-2000EU",
        recommendedRoomArea: "23",
        generalCharacteristics: {
            heaterType: "відкритий",
            installation: "З коліщатками/ніжками для переміщення/настінне",
            additionalCharacteristics: "Швидке і безшумне обігрівання. Робота за принципом природної конвекції повітря. Європейський нагрівальний елемент. Подвійна потужність нагрівального елементу з можливістю використання тільки 50%. Режим підтримки мінімальної температури +8 °C. Ручка для перенесення",
            // temperatureRange: "Від -15 °С до + 50 °С",
            internalBlockSize: "46 х 80 х 11.5",
            externalBlockSize: "50 х 99 х 12.5",
            weightInternalUnit: "5,4",
            weightExternalUnit: "6,4",
            remoteControl: "-",
            bodyColor: "Білий",
            madeIn: "Україна",
            brandCountry: "Germany",
            guarantee: "60",
            //         coolingCapacity: "3.5 kW",
            //         heatingCapacity: "3.5 kW",
            //         energyClass: "A++",
            //  Compressor type       noiseLevel: "21 dB",
            //         inverter: true,
            //         wifiControl: true,
            //         color: "White",
        },
        functions: {
            operationModes: "Обігрів",
            // turboMode: "+",
            // nightMode: "+",
            timer: "-",
            // adjustingBlindsVertically: "+",
            // automaticRestart: "+",
            // selfCleaning: "+",
            // disablingDisplayLighting: "+",
            // dustFilter: "+",
        },

        

        specifications: {
            // powerBto: "7000",
            // coolingCapacity: "2,345",
            // heatingCapacity: "2,433",
            // SEER: "5.2",
            // SCOP: "3.5",
            // consumerPowerCoolingW: "730 (100~1074)",
            protectionClass: "IP20",
            consumerPowerHeatingW: "2000",
            // energyClass: "A/A",
            // noiseLevelIndoorUnit: "35/30,5/24,5/22",
            // noiseLevelOutdoorUnit: "52,5",
            // heatExchangersCoating: "Гідрофільне",
            // MoistureRemoval: "1,0",
            // MaximumConsumerCurrent: "9,0",
            // powerSupply: "Indoor unit",
            // connectingPipesDimensions: "6,35/9,52",
            // highwayMaximumLength: "25",
            // highwayMaximumHeightDifference: "10",
            // freon: "R32",
            // freonWeight: "0,42",
            completeSet: "Конвектор, ніжки (2 шт.), кронштейни для настінного монтажу, інструкція",
            images: {
                indoorUnit: "",
                outdoorUnit: "",
            },

            downloads: {
                userManual: "",
            },

            // availability: true,
            // stock: 25,
            // ratings: {
            //     average: 4.7,
            //     reviews: 145,
            // },
            
        },
    },

    {
        id: 83,
        btiIdx: 89,
        art: "#889346",
        name: "RODA Standart+ RSP-2500EU",
        brand: "RODA",
        model: "RSP-2500EU",
        price: "2299",
        discount: "-",
        available: true,
        description:
            "Конвектор RODA Standart+ RSP-2500EU",
        recommendedRoomArea: "28",
        generalCharacteristics: {
            heaterType: "відкритий",
            installation: "З коліщатками/ніжками для переміщення/настінне",
            additionalCharacteristics: "Швидке і безшумне обігрівання. Робота за принципом природної конвекції повітря. Європейський нагрівальний елемент. Подвійна потужність нагрівального елементу з можливістю використання тільки 50%. Режим підтримки мінімальної температури +8 °C. Ручка для перенесення",
            // temperatureRange: "Від -15 °С до + 50 °С",
            internalBlockSize: "46х105.5х11.5",
            externalBlockSize: "50х112х12.5",
            weightInternalUnit: "6,2",
            weightExternalUnit: "7,2",
            remoteControl: "-",
            bodyColor: "Білий",
            madeIn: "Україна",
            brandCountry: "Germany",
            guarantee: "60",
            //         coolingCapacity: "3.5 kW",
            //         heatingCapacity: "3.5 kW",
            //         energyClass: "A++",
            //  Compressor type       noiseLevel: "21 dB",
            //         inverter: true,
            //         wifiControl: true,
            //         color: "White",
        },
        functions: {
            operationModes: "Обігрів",
            // turboMode: "+",
            // nightMode: "+",
            timer: "-",
            // adjustingBlindsVertically: "+",
            // automaticRestart: "+",
            // selfCleaning: "+",
            // disablingDisplayLighting: "+",
            // dustFilter: "+",
        },

        

        specifications: {
            // powerBto: "7000",
            // coolingCapacity: "2,345",
            // heatingCapacity: "2,433",
            // SEER: "5.2",
            // SCOP: "3.5",
            // consumerPowerCoolingW: "730 (100~1074)",
            protectionClass: "IP20",
            consumerPowerHeatingW: "2500",
            // energyClass: "A/A",
            // noiseLevelIndoorUnit: "35/30,5/24,5/22",
            // noiseLevelOutdoorUnit: "52,5",
            // heatExchangersCoating: "Гідрофільне",
            // MoistureRemoval: "1,0",
            // MaximumConsumerCurrent: "9,0",
            // powerSupply: "Indoor unit",
            // connectingPipesDimensions: "6,35/9,52",
            // highwayMaximumLength: "25",
            // highwayMaximumHeightDifference: "10",
            // freon: "R32",
            // freonWeight: "0,42",
            completeSet: "Конвектор, ніжки (2 шт.), кронштейни для настінного монтажу, інструкція",
            images: {
                indoorUnit: "",
                outdoorUnit: "",
            },

            downloads: {
                userManual: "",
            },

            // availability: true,
            // stock: 25,
            // ratings: {
            //     average: 4.7,
            //     reviews: 145,
            // },
            
        },
    },
    {
        id: 84,
        btiIdx: 90,
        art: "#889347",
        name: "Roda RCP-1000EU",
        brand: "RODA",
        model: "RCP-1000EU",
        price: "5799",
        discount: "-",
        available: true,
        description:
            "Керамічний обігрівач Roda RCP-1000EU",
        recommendedRoomArea: "20",
        generalCharacteristics: {
            // heaterType: "відкритий",
            installation: "настінне/підлогове (пілогові опори можна придбати окремо)",
            additionalCharacteristics: "Швидке і безшумне обігрівання",
            // temperatureRange: "Від -15 °С до + 50 °С",
            // internalBlockSize: "60 х 120 х 6,5",
            externalBlockSize: "60 x 60 x 6,5",
            // weightInternalUnit: "6,2",
            weightExternalUnit: "28,3",
            remoteControl: "-",
            bodyColor: "Білий",
            madeIn: "Україна",
            brandCountry: "Germany",
            guarantee: "60",
            //         coolingCapacity: "3.5 kW",
            //         heatingCapacity: "3.5 kW",
            //         energyClass: "A++",
            //  Compressor type       noiseLevel: "21 dB",
            //         inverter: true,
            //         wifiControl: true,
            //         color: "White",
        },
        functions: {
            operationModes: "Обігрів",
            // turboMode: "+",
            // nightMode: "+",
            timer: "-",
            // adjustingBlindsVertically: "+",
            // automaticRestart: "+",
            // selfCleaning: "+",
            // disablingDisplayLighting: "+",
            // dustFilter: "+",
        },

        

        specifications: {
            // powerBto: "7000",
            // coolingCapacity: "2,345",
            // heatingCapacity: "2,433",
            // SEER: "5.2",
            // SCOP: "3.5",
            // consumerPowerCoolingW: "730 (100~1074)",
            protectionClass: "IP44",
            consumerPowerHeatingW: "1000",
            // energyClass: "A/A",
            // noiseLevelIndoorUnit: "35/30,5/24,5/22",
            // noiseLevelOutdoorUnit: "52,5",
            // heatExchangersCoating: "Гідрофільне",
            // MoistureRemoval: "1,0",
            // MaximumConsumerCurrent: "9,0",
            // powerSupply: "Indoor unit",
            // connectingPipesDimensions: "6,35/9,52",
            // highwayMaximumLength: "25",
            // highwayMaximumHeightDifference: "10",
            // freon: "R32",
            // freonWeight: "0,42",
            completeSet: "Конвектор, комплект для кріплення на стіну, інструкція, гарантійний талон",
            images: {
                indoorUnit: "",
                outdoorUnit: "",
            },

            downloads: {
                userManual: "",
            },

            // availability: true,
            // stock: 25,
            // ratings: {
            //     average: 4.7,
            //     reviews: 145,
            // },
            
        },
    },
    {
        id: 86,
        btiIdx: 92,
        art: "#889349",
        name: "Roda RCP-500EU",
        brand: "RODA",
        model: "RCP-500EU",
        price: "2999",
        discount: "-",
        available: true,
        description:
            "Керамічний обігрівач Roda RCP-500EU",
        recommendedRoomArea: "10",
        generalCharacteristics: {
            // heaterType: "відкритий",
            installation: "настінне/підлогове (пілогові опори можна придбати окремо)",
            additionalCharacteristics: "Швидке і безшумне обігрівання",
            // temperatureRange: "Від -15 °С до + 50 °С",
            // internalBlockSize: "60 х 120 х 6,5",
            externalBlockSize: "60 x 60 x 6,5",
            // weightInternalUnit: "6,2",
            weightExternalUnit: "16,9",
            remoteControl: "-",
            bodyColor: "Білий",
            madeIn: "Україна",
            brandCountry: "Germany",
            guarantee: "60",
            //         coolingCapacity: "3.5 kW",
            //         heatingCapacity: "3.5 kW",
            //         energyClass: "A++",
            //  Compressor type       noiseLevel: "21 dB",
            //         inverter: true,
            //         wifiControl: true,
            //         color: "White",
        },
        functions: {
            operationModes: "Обігрів",
            // turboMode: "+",
            // nightMode: "+",
            timer: "-",
            // adjustingBlindsVertically: "+",
            // automaticRestart: "+",
            // selfCleaning: "+",
            // disablingDisplayLighting: "+",
            // dustFilter: "+",
        },

        

        specifications: {
            // powerBto: "7000",
            // coolingCapacity: "2,345",
            // heatingCapacity: "2,433",
            // SEER: "5.2",
            // SCOP: "3.5",
            // consumerPowerCoolingW: "730 (100~1074)",
            protectionClass: "IP44",
            consumerPowerHeatingW: "500",
            // energyClass: "A/A",
            // noiseLevelIndoorUnit: "35/30,5/24,5/22",
            // noiseLevelOutdoorUnit: "52,5",
            // heatExchangersCoating: "Гідрофільне",
            // MoistureRemoval: "1,0",
            // MaximumConsumerCurrent: "9,0",
            // powerSupply: "Indoor unit",
            // connectingPipesDimensions: "6,35/9,52",
            // highwayMaximumLength: "25",
            // highwayMaximumHeightDifference: "10",
            // freon: "R32",
            // freonWeight: "0,42",
            completeSet: "Конвектор, комплект для кріплення на стіну, інструкція, гарантійний талон",
            images: {
                indoorUnit: "",
                outdoorUnit: "",
            },

            downloads: {
                userManual: "",
            },

            // availability: true,
            // stock: 25,
            // ratings: {
            //     average: 4.7,
            //     reviews: 145,
            // },
            
        },
    },
]

    